= jMonkeyEngine Documentation

image:https://github.com/mitm001/jme-wiki/workflows/Build%20Docs/badge.svg[Status Badge, 175, 25]

see link:https://mitm001.github.io/jme-wiki/[https://wiki.jmonkeyengine.org/]

The project to store, edit, and generate the documentation of http://jmonkeyengine.org[jMonkeyEngine].

The documentation in `docs/modules/` is editable :

* Online via github (Edit link located on the top navbar of the Wiki + Pull Request)
* Offline with the Atom editor, which includes a built in previewer and code editor. see xref:docs-wiki/modules/ROOT/pages/atom_editor.adoc[Atom Editor for Wiki Editing]
* Any text editor and browser program of your choice.
* Setting up your own local Node.js environment.

NOTE: Read the xref:docs-wiki/modules/ROOT/pages/wiki_contributor.adoc[Wiki Contributions].

== Build & Preview

To set up the Antora environment, you'll need Nodejs (tested with node 12).

From your local wiki directory.

Run:
```
npm install
npm run buildDocs
```

This will install the needed dependencies and run the static site generator. The documentation will be output to the directory `build/site`.

To preview, navigate to the `build/site` directory and open the index.html file in your browser.

See also: https://docs.antora.org/antora/2.3/preview-site/
